import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import AuthProvider from "@/components/AuthProvider";

const IranYekan = localFont({
    variable: "--font-iranYekan",
    // src: '../fonts/eot/iranyekanwebextraboldfanum.woff',
    display: "swap",
    src: [
        {
            path: "../fonts/woff/iranyekanwebboldfanum.woff",
            weight: "100",
            style: "normal",
        },
        {
            path: "../fonts/woff/iranyekanwebthinfanum.woff",
            weight: "300",
            style: "normal",
        },
        {
            path: "../fonts/woff/iranyekanwebregularfanum.woff",
            weight: "400",
            style: "normal",
        },
        {
            path: "../fonts/woff/iranyekanwebmediumfanum.woff",
            weight: "500",
            style: "normal",
        },
        {
            path: "../fonts/woff/iranyekanwebextraboldfanum.woff",
            weight: "800",
            style: "normal",
        },
        {
            path: "../fonts/woff/iranyekanwebextrablackfanum.woff",
            weight: "900",
            style: "normal",
        },
    ],
});

export const metadata: Metadata = {
    title: "پیتزا وای فای| سفارش آنلاین پیتزا",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <html lang="fa" dir="rtl">
                <body className={`${IranYekan.variable} font-sans bg-primary`}>
                    <main className="mx-auto">
                        <Header />
                        {children}
                        <Footer />
                    </main>
                </body>
            </html>
        </AuthProvider>
    );
}
